### ISSUE TITLE
adding a full album

### ISSUE THREAD

**Issue by eephyne** [mistic100/Piwigo-User-Collections#3]
Hello

First of all thanks a lot for your plugin, its the only one that fullfill my need to easily share a collection of photos.

I only lack one thing (well two but...) its the ability do add a full album to a collection (I can't see myself adding more than 300 photos manually <<).

the others thing is to add sub-collection ( album inside collections) but I don't even know if thats possible.

either way thanks for your time :)

(for the first request if you don't have the time to do it, could you please tell me where to look so I can try to do it myself even if I'm clearly not used to php and piwigo.)

**Comment by mistic100** [comment]
working on adding full album

I won't add sub-collections

**Comment by eephyne** [comment]
Nice to know :)
