### ISSUE TITLE
Sharing to guest

### ISSUE THREAD

**Issue by eephyne** [mistic100/Piwigo-User-Collections#4]
Hi again

I just tested the share option (it's the main reason I want this plugin) and noticed that the link isn't working unless you're logged in. I assume this is because the photo are not public but it kind of kill the feature (at least for me).

Is it possible to bypass that or not? (I do not want to make photo public by default)

Thanks

**Comment by eephyne** [comment]
well it seem to work on desktop but not on mobile

**Comment by mistic100** [comment]
the entire plugin is disabled on mobile #2
